/******************************************************************************
 * Copyright (C) 2022 dyifm.com
 * This file is part of FM3-public <https://github.com/dyifm/fm3-public>.
 *
 * fm3-public is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * fm3-public is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with fm3-public.  If not, see <http://www.gnu.org/licenses/>.
 *******************************************************************************/
#ifndef VERSION_H
#define VERSION_H

// DO NOT MODIFY - AUTOGENERATED -

#include <Arduino.h>

struct TVersion
{
    int major = 0;
    int minor = 1;
    int patch = 259;
    String buildDateTime = "2022-01-24T01:39:58.635838";
    String stringVersion = "0.1.259";
    String stringVersionDateTime = "0.1.259+2022-01-24T01:39:58.635838";
};

#ifndef APPVERSION
const TVersion APPVERSION;
#endif

#endif
